name:                algeometry
version:             0.1.0.0
github:              "githubuser/algeometry"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/algeometry#readme>

dependencies:
- base >= 4.15 && < 5
- containers
- lucid
- lucid-svg
- process
- text
- tasty >= 1.4.2 && < 1.5
- tasty-quickcheck >= 0.10 && < 0.12
- QuickCheck >= 2.14.2 && < 2.15
- array >= 0.5.4
- template-haskell >= 2.19
- ghc-prim >= 0.9
- MonadRandom
    
ghc-options:
  - -Wdefault
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wunused-imports
# - -Wcompat
# - -Widentities
# - -Wincomplete-record-updates
# - -Wmissing-export-lists
# - -Wmissing-home-modules
# - -Wpartial-fields
# - -Wname-shadowing


library:
  source-dirs: src

executables:    
  sphere4d:
    main:                sphere4d.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algeometry
    
  caleidoscope:
    main:                caleidoscope.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algeometry

  moebius:
    main:                moebius.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algeometry

  menelaus:
    main:                menelaus.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algeometry
    
  duals:
    main:                duals.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algeometry

    
tests:
  algeometry-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algeometry
    - tasty >= 1.4.2 && < 1.5
    - tasty-hunit >= 0.10 && < 0.12
    - tasty-quickcheck >= 0.10 && < 0.12
    - QuickCheck >= 2.14.2 && < 2.15
